# docker-compose.yml
#
# This file is the Docker Compose configuration that used to be for only public networks - serves IREM data.
# It defines the volumes and networks that are shared across all services.

volumes:
  app_data:
    name: app_data
    driver: local
  grafana_data:
    name: grafana_data
    driver: local
  influxdb_data:
    name: influxdb_data
    driver: local
  influxdb_config_data:
    name: influxdb_config_data
    driver: local

networks:
  app_network:
    name: app_network
    driver: bridge

services:
  app:
    extends:
      file: ./docker-compose/docker-compose.app.yml
      service: app
    container_name: app-default
    image: app-default:latest
    environment:
      - IS_USING_IREM=1
      - IS_USING_RADEM=0

  grafana:
    extends:
      file: ./docker-compose/docker-compose.grafana.yml
      service: grafana
    container_name: grafana-default
    ports:
      - "51820:3000"
    volumes:
      - ./grafana/grafana.default.ini:/etc/grafana/grafana.ini

  grafana-init-users:
    extends:
      file: ./docker-compose/docker-compose.grafana-init-users.yml
      service: grafana-init-users

  cadvisor:
    extends:
      file: ./docker-compose/docker-compose.cadvisor.yml
      service: cadvisor

  node-exporter:
    extends:
      file: ./docker-compose/docker-compose.node-exporter.yml
      service: node-exporter

  prometheus:
    extends:
      file: ./docker-compose/docker-compose.prometheus.yml
      service: prometheus

  influxdb:
    extends:
      file: ./docker-compose/docker-compose.influxdb.yml
      service: influxdb
