# docker-compose.legacy.yml (previously named private)
#
# This file is the Docker Compose configuration for private networks (those with access to RADEM data, which as of now (24.07.2025) is unavailable).
# It defines the volumes and networks that are shared across all services.

volumes:
  app_data:
    driver: local
  grafana_data:
    driver: local
  influxdb_data:
    driver: local
  influxdb_config_data:
    driver: local

networks:
  app_network:
    driver: bridge

services:
  app:
    extends:
      file: ./docker-compose/docker-compose.app.yml
      service: app
    container_name: app-legacy

  grafana:
    extends:
      file: ./docker-compose/docker-compose.grafana.yml
      service: grafana
    container_name: grafana-legacy
    ports:
      - "81:3000"
    volumes:
      - ./grafana/grafana.legacy.ini:/etc/grafana/grafana.ini

  grafana-init-users:
    extends:
      file: ./docker-compose/docker-compose.grafana-init-users.yml
      service: grafana-init-users

  cadvisor:
    extends:
      file: ./docker-compose/docker-compose.cadvisor.yml
      service: cadvisor

  node-exporter:
    extends:
      file: ./docker-compose/docker-compose.node-exporter.yml
      service: node-exporter

  prometheus:
    extends:
      file: ./docker-compose/docker-compose.prometheus.yml
      service: prometheus

  influxdb:
    extends:
      file: ./docker-compose/docker-compose.influxdb.yml
      service: influxdb
