# docker-compose.radem.yml
#
# This file is the Docker Compose configuration for the RADEM environment.
# It defines the volumes and networks that are shared across all services.

volumes:
  app_data:
    driver: local
  grafana_data:
    driver: local
  influxdb_data:
    driver: local
  influxdb_config_data:
    driver: local
  prometheus_data:
    driver: local
  elastic_data:
    driver: local

networks:
  app_network:
    name: app_network
    driver: bridge
    enable_ipv6: false

services:
  app:
    extends:
      file: ./docker-compose/docker-compose.app.yml
      service: app
    container_name: app-radem
    image: app-default:latest
    environment:
      - IS_USING_IREM=0
      - IS_USING_RADEM=1

  grafana:
    extends:
      file: ./docker-compose/docker-compose.grafana.yml
      service: grafana
    container_name: grafana-radem
    ports:
      - "80:3000"
    volumes:
      - ./grafana/grafana.radem.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards/specific/RADEM:/etc/grafana/dashboards/specific

  grafana-init-users:
    extends:
      file: ./docker-compose/docker-compose.grafana-init-users.yml
      service: grafana-init-users

  cadvisor:
    extends:
      file: ./docker-compose/docker-compose.cadvisor.yml
      service: cadvisor

  node-exporter:
    extends:
      file: ./docker-compose/docker-compose.node-exporter.yml
      service: node-exporter

  prometheus:
    extends:
      file: ./docker-compose/docker-compose.prometheus.yml
      service: prometheus

  influxdb:
    extends:
      file: ./docker-compose/docker-compose.influxdb.yml
      service: influxdb

  elasticsearch:
    extends:
      file: ./docker-compose/docker-compose.elasticsearch.yml
      service: elasticsearch

  logstash:
    extends:
      file: ./docker-compose/docker-compose.logstash.yml
      service: logstash

  kibana:
    extends:
      file: ./docker-compose/docker-compose.kibana.yml
      service: kibana
