# docker-compose.influxdb.yml
#
# This service is responsible for running the InfluxDB database.

services:
  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - app_data:/app_data
      - influxdb_config_data:/etc/influxdb2
      - influxdb_data:/var/lib/influxdb2
    networks:
      - app_network
    ports:
      - "8186:8086"
    restart: unless-stopped
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:5000"
    depends_on:
      logstash:
        condition: service_healthy
