# docker-compose.grafana-init-users.yml
#
# This service is responsible for initializing Grafana with a viewer user by using the Grafana API.
# It waits for Grafana to be ready and then creates a user with viewer permissions. This is
# necessary because the Grafana does not support user provisioning.

services:
  grafana-init-users:
    container_name: grafana-init-users
    image: curlimages/curl:latest
    depends_on:
      grafana:
        condition: service_started
      logstash:
        condition: service_healthy
    volumes:
      - ../grafana/scripts/init_users.sh:/init_users.sh
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_VIEWER_LOGIN: ${GF_VIEWER_LOGIN}
      GF_VIEWER_PASSWORD: ${GF_VIEWER_PASSWORD}
    entrypoint: ["/bin/sh", "/init_users.sh"]
    networks:
      - app_network
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:5000"
