services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      #- ELASTICSEARCH_USERNAME=${KIBANA_ELASTICSEARCH_USERNAME}
      #- ELASTICSEARCH_PASSWORD=${KIBANA_ELASTICSEARCH_PASSWORD}
    depends_on:
      - elasticsearch
    networks:
      - app_network
    restart: unless-stopped
