# docker-compose.grafana.yml
#
# This service is responsible for running the Grafana dashboard.

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      URL_GRAFANA: http://grafana:3000
      URL_INFLUXDB: http://influxdb:8086
      URL_PROMETHEUS: http://prometheus:9090
      INFLUXDB_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      INFLUXDB_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      INFLUXDB_ORG: ${DOCKER_INFLUXDB_INIT_ORG}
      INFLUXDB_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
      INFLUXDB_IREM_BUCKET: ${DOCKER_INFLUXDB_INIT_IREM_BUCKET}
    volumes:
      - grafana_data:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/etc/grafana/dashboards
      - ../grafana/grafana.legacy.ini:/etc/grafana/grafana.ini
    networks:
      - app_network
    ports:
      - "81:3000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
